/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SmsMarketingPolicyRouteImport } from './routes/sms-marketing-policy'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as HbeRouteImport } from './routes/hbe'
import { Route as FindRouteImport } from './routes/find'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventSignupRouteImport } from './routes/event-signup'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AgeVerificationPolicyRouteImport } from './routes/age-verification-policy'
import { Route as AccessibilityStatementRouteImport } from './routes/accessibility-statement'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSlugRouteImport } from './routes/products_.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicNewsletterRouteImport } from './routes/api/public/newsletter'
import { Route as ApiPublicEventSignupRouteImport } from './routes/api/public/event-signup'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsMarketingPolicyRoute = SmsMarketingPolicyRouteImport.update({
  id: '/sms-marketing-policy',
  path: '/sms-marketing-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HbeRoute = HbeRouteImport.update({
  id: '/hbe',
  path: '/hbe',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSignupRoute = EventSignupRouteImport.update({
  id: '/event-signup',
  path: '/event-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeVerificationPolicyRoute = AgeVerificationPolicyRouteImport.update({
  id: '/age-verification-policy',
  path: '/age-verification-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityStatementRoute = AccessibilityStatementRouteImport.update({
  id: '/accessibility-statement',
  path: '/accessibility-statement',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products_/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsletterRoute = ApiPublicNewsletterRouteImport.update({
  id: '/api/public/newsletter',
  path: '/api/public/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventSignupRoute = ApiPublicEventSignupRouteImport.update({
  id: '/api/public/event-signup',
  path: '/api/public/event-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility-statement': typeof AccessibilityStatementRoute
  '/age-verification-policy': typeof AgeVerificationPolicyRoute
  '/contact': typeof ContactRoute
  '/event-signup': typeof EventSignupRoute
  '/faq': typeof FaqRoute
  '/find': typeof FindRoute
  '/hbe': typeof HbeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sms-marketing-policy': typeof SmsMarketingPolicyRoute
  '/social': typeof SocialRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/event-signup': typeof ApiPublicEventSignupRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility-statement': typeof AccessibilityStatementRoute
  '/age-verification-policy': typeof AgeVerificationPolicyRoute
  '/contact': typeof ContactRoute
  '/event-signup': typeof EventSignupRoute
  '/faq': typeof FaqRoute
  '/find': typeof FindRoute
  '/hbe': typeof HbeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sms-marketing-policy': typeof SmsMarketingPolicyRoute
  '/social': typeof SocialRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/event-signup': typeof ApiPublicEventSignupRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility-statement': typeof AccessibilityStatementRoute
  '/age-verification-policy': typeof AgeVerificationPolicyRoute
  '/contact': typeof ContactRoute
  '/event-signup': typeof EventSignupRoute
  '/faq': typeof FaqRoute
  '/find': typeof FindRoute
  '/hbe': typeof HbeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sms-marketing-policy': typeof SmsMarketingPolicyRoute
  '/social': typeof SocialRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/products_/$slug': typeof ProductsSlugRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/event-signup': typeof ApiPublicEventSignupRoute
  '/api/public/newsletter': typeof ApiPublicNewsletterRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility-statement'
    | '/age-verification-policy'
    | '/contact'
    | '/event-signup'
    | '/faq'
    | '/find'
    | '/hbe'
    | '/privacy-policy'
    | '/products'
    | '/refund-policy'
    | '/shipping-policy'
    | '/sms-marketing-policy'
    | '/social'
    | '/terms-of-service'
    | '/email/unsubscribe'
    | '/products/$slug'
    | '/api/public/contact'
    | '/api/public/event-signup'
    | '/api/public/newsletter'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility-statement'
    | '/age-verification-policy'
    | '/contact'
    | '/event-signup'
    | '/faq'
    | '/find'
    | '/hbe'
    | '/privacy-policy'
    | '/products'
    | '/refund-policy'
    | '/shipping-policy'
    | '/sms-marketing-policy'
    | '/social'
    | '/terms-of-service'
    | '/email/unsubscribe'
    | '/products/$slug'
    | '/api/public/contact'
    | '/api/public/event-signup'
    | '/api/public/newsletter'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility-statement'
    | '/age-verification-policy'
    | '/contact'
    | '/event-signup'
    | '/faq'
    | '/find'
    | '/hbe'
    | '/privacy-policy'
    | '/products'
    | '/refund-policy'
    | '/shipping-policy'
    | '/sms-marketing-policy'
    | '/social'
    | '/terms-of-service'
    | '/email/unsubscribe'
    | '/products_/$slug'
    | '/api/public/contact'
    | '/api/public/event-signup'
    | '/api/public/newsletter'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityStatementRoute: typeof AccessibilityStatementRoute
  AgeVerificationPolicyRoute: typeof AgeVerificationPolicyRoute
  ContactRoute: typeof ContactRoute
  EventSignupRoute: typeof EventSignupRoute
  FaqRoute: typeof FaqRoute
  FindRoute: typeof FindRoute
  HbeRoute: typeof HbeRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProductsRoute: typeof ProductsRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  SmsMarketingPolicyRoute: typeof SmsMarketingPolicyRoute
  SocialRoute: typeof SocialRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicEventSignupRoute: typeof ApiPublicEventSignupRoute
  ApiPublicNewsletterRoute: typeof ApiPublicNewsletterRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-marketing-policy': {
      id: '/sms-marketing-policy'
      path: '/sms-marketing-policy'
      fullPath: '/sms-marketing-policy'
      preLoaderRoute: typeof SmsMarketingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hbe': {
      id: '/hbe'
      path: '/hbe'
      fullPath: '/hbe'
      preLoaderRoute: typeof HbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-signup': {
      id: '/event-signup'
      path: '/event-signup'
      fullPath: '/event-signup'
      preLoaderRoute: typeof EventSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age-verification-policy': {
      id: '/age-verification-policy'
      path: '/age-verification-policy'
      fullPath: '/age-verification-policy'
      preLoaderRoute: typeof AgeVerificationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility-statement': {
      id: '/accessibility-statement'
      path: '/accessibility-statement'
      fullPath: '/accessibility-statement'
      preLoaderRoute: typeof AccessibilityStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$slug': {
      id: '/products_/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter': {
      id: '/api/public/newsletter'
      path: '/api/public/newsletter'
      fullPath: '/api/public/newsletter'
      preLoaderRoute: typeof ApiPublicNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/event-signup': {
      id: '/api/public/event-signup'
      path: '/api/public/event-signup'
      fullPath: '/api/public/event-signup'
      preLoaderRoute: typeof ApiPublicEventSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityStatementRoute: AccessibilityStatementRoute,
  AgeVerificationPolicyRoute: AgeVerificationPolicyRoute,
  ContactRoute: ContactRoute,
  EventSignupRoute: EventSignupRoute,
  FaqRoute: FaqRoute,
  FindRoute: FindRoute,
  HbeRoute: HbeRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProductsRoute: ProductsRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  SmsMarketingPolicyRoute: SmsMarketingPolicyRoute,
  SocialRoute: SocialRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicEventSignupRoute: ApiPublicEventSignupRoute,
  ApiPublicNewsletterRoute: ApiPublicNewsletterRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
