/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SmsMarketingPolicyRouteImport } from './routes/sms-marketing-policy'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OghomeRouteImport } from './routes/oghome'
import { Route as HbeRouteImport } from './routes/hbe'
import { Route as FindRouteImport } from './routes/find'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventSignupRouteImport } from './routes/event-signup'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AgeVerificationPolicyRouteImport } from './routes/age-verification-policy'
import { Route as AccessibilityStatementRouteImport } from './routes/accessibility-statement'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSlugRouteImport } from './routes/products_.$slug'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsMarketingPolicyRoute = SmsMarketingPolicyRouteImport.update({
  id: '/sms-marketing-policy',
  path: '/sms-marketing-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OghomeRoute = OghomeRouteImport.update({
  id: '/oghome',
  path: '/oghome',
  getParentRoute: () => rootRouteImport,
} as any)
const HbeRoute = HbeRouteImport.update({
  id: '/hbe',
  path: '/hbe',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSignupRoute = EventSignupRouteImport.update({
  id: '/event-signup',
  path: '/event-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeVerificationPolicyRoute = AgeVerificationPolicyRouteImport.update({
  id: '/age-verification-policy',
  path: '/age-verification-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityStatementRoute = AccessibilityStatementRouteImport.update({
  id: '/accessibility-statement',
  path: '/accessibility-statement',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products_/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility-statement': typeof AccessibilityStatementRoute
  '/age-verification-policy': typeof AgeVerificationPolicyRoute
  '/contact': typeof ContactRoute
  '/event-signup': typeof EventSignupRoute
  '/faq': typeof FaqRoute
  '/find': typeof FindRoute
  '/hbe': typeof HbeRoute
  '/oghome': typeof OghomeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sms-marketing-policy': typeof SmsMarketingPolicyRoute
  '/social': typeof SocialRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility-statement': typeof AccessibilityStatementRoute
  '/age-verification-policy': typeof AgeVerificationPolicyRoute
  '/contact': typeof ContactRoute
  '/event-signup': typeof EventSignupRoute
  '/faq': typeof FaqRoute
  '/find': typeof FindRoute
  '/hbe': typeof HbeRoute
  '/oghome': typeof OghomeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sms-marketing-policy': typeof SmsMarketingPolicyRoute
  '/social': typeof SocialRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility-statement': typeof AccessibilityStatementRoute
  '/age-verification-policy': typeof AgeVerificationPolicyRoute
  '/contact': typeof ContactRoute
  '/event-signup': typeof EventSignupRoute
  '/faq': typeof FaqRoute
  '/find': typeof FindRoute
  '/hbe': typeof HbeRoute
  '/oghome': typeof OghomeRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/sms-marketing-policy': typeof SmsMarketingPolicyRoute
  '/social': typeof SocialRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/products_/$slug': typeof ProductsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility-statement'
    | '/age-verification-policy'
    | '/contact'
    | '/event-signup'
    | '/faq'
    | '/find'
    | '/hbe'
    | '/oghome'
    | '/privacy-policy'
    | '/products'
    | '/refund-policy'
    | '/shipping-policy'
    | '/sms-marketing-policy'
    | '/social'
    | '/terms-of-service'
    | '/products/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility-statement'
    | '/age-verification-policy'
    | '/contact'
    | '/event-signup'
    | '/faq'
    | '/find'
    | '/hbe'
    | '/oghome'
    | '/privacy-policy'
    | '/products'
    | '/refund-policy'
    | '/shipping-policy'
    | '/sms-marketing-policy'
    | '/social'
    | '/terms-of-service'
    | '/products/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility-statement'
    | '/age-verification-policy'
    | '/contact'
    | '/event-signup'
    | '/faq'
    | '/find'
    | '/hbe'
    | '/oghome'
    | '/privacy-policy'
    | '/products'
    | '/refund-policy'
    | '/shipping-policy'
    | '/sms-marketing-policy'
    | '/social'
    | '/terms-of-service'
    | '/products_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityStatementRoute: typeof AccessibilityStatementRoute
  AgeVerificationPolicyRoute: typeof AgeVerificationPolicyRoute
  ContactRoute: typeof ContactRoute
  EventSignupRoute: typeof EventSignupRoute
  FaqRoute: typeof FaqRoute
  FindRoute: typeof FindRoute
  HbeRoute: typeof HbeRoute
  OghomeRoute: typeof OghomeRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProductsRoute: typeof ProductsRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  SmsMarketingPolicyRoute: typeof SmsMarketingPolicyRoute
  SocialRoute: typeof SocialRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-marketing-policy': {
      id: '/sms-marketing-policy'
      path: '/sms-marketing-policy'
      fullPath: '/sms-marketing-policy'
      preLoaderRoute: typeof SmsMarketingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oghome': {
      id: '/oghome'
      path: '/oghome'
      fullPath: '/oghome'
      preLoaderRoute: typeof OghomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hbe': {
      id: '/hbe'
      path: '/hbe'
      fullPath: '/hbe'
      preLoaderRoute: typeof HbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-signup': {
      id: '/event-signup'
      path: '/event-signup'
      fullPath: '/event-signup'
      preLoaderRoute: typeof EventSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age-verification-policy': {
      id: '/age-verification-policy'
      path: '/age-verification-policy'
      fullPath: '/age-verification-policy'
      preLoaderRoute: typeof AgeVerificationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility-statement': {
      id: '/accessibility-statement'
      path: '/accessibility-statement'
      fullPath: '/accessibility-statement'
      preLoaderRoute: typeof AccessibilityStatementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$slug': {
      id: '/products_/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityStatementRoute: AccessibilityStatementRoute,
  AgeVerificationPolicyRoute: AgeVerificationPolicyRoute,
  ContactRoute: ContactRoute,
  EventSignupRoute: EventSignupRoute,
  FaqRoute: FaqRoute,
  FindRoute: FindRoute,
  HbeRoute: HbeRoute,
  OghomeRoute: OghomeRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProductsRoute: ProductsRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  SmsMarketingPolicyRoute: SmsMarketingPolicyRoute,
  SocialRoute: SocialRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ProductsSlugRoute: ProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
